### PR TITLE
add step adjustment to the walkingModule

### PR DESCRIPTION
**Pull request by MiladShafiee**
In this pull request we add the step adaptation library inside the walking Module.

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Should we put push recovery in bipedal-locomotion-controllers? 

@danielepucci

**Comment by DanielePucci** [comment]
In my opinion, yes 

CC
@S-Dafarra

**Comment by S-Dafarra** [comment]
In my opinion, we could start from https://github.com/MiladShafiee/walking-controllers/pull/2 instead since that PR has only additions and it should be easier. Then, I would split this PR into two: one containing only the additions (which can go in ``bipedal-locomotion-controllers``) and another one with the modifications to the existing code (e.g. modifications to the walking module, which cannot be extracted).

Anyway, I think that it is easier to discuss this f2f, so that we can easily show to @MiladShafiee what h would need to do.

**Comment by MiladShafiee** [comment]
> In my opinion, we could start from #2 instead since that PR has only additions and it should be easier. Then, I would split this PR into two: one containing only the additions (which can go in bipedal-locomotion-controllers) and another one with the modifications to the existing code (e.g. modifications to the walking module, which cannot be extracted).

I agree, I think the #2 will go to bipedal locomotion controllers repository as a library. Then this pull request is related to how to use it in walking Module that can be added in the walking controller repository.

**Comment by MiladShafiee** [comment]
We close this pill request since we have changed the step adaptation library that is not consistent with this pull request, so we have opened a new pull request https://github.com/MiladShafiee/walking-controller.s/pull/4

**Pull request closed without merging**
